{{- if .Values.serviceAccount.create -}}
# harness.io/skip-file-for-deploy
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildachart.serviceAccountName" . }}
  labels:
    {{- include "buildachart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
